config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  get 'sessions/new'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :pictures
  resources :favorites, only: [:create, :destroy, :index]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.production?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :title, :content, presence:true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # mount_uploader :image, ImageUploader
  mount_uploader :profile_image, ImageUploader
  validates :name,  presence: true, length: { maximum: 30 }
  validates :mail, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { mail.downcase! }

  # require 'io/console'
  # password = STDIN.noecho(&:gets)

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :favorites, dependent: :destroy
  has_many :pictures


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @user = current_user
    @favorites = Favorite.where(user_id: @user.id).all
    # @favorite = Favorite.last
    # @favorites.current_user.id
  end

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id

    respond_to do |format|
      if @picture.save
        ContactMailer.contact_mail(@picture).deliver
        format.html { redirect_to @picture, notice: '新しく投稿されました' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: '更新されました' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: '削除されました' }
      format.json { head :no_content }
    end
  end

  private

  def ensure_correct_user
    @picture = Picture.find_by(id: params[:id])
    if current_user.id != @picture.user_id
      redirect_to pictures_url
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_picture
    @picture = Picture.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def picture_params
    params.require(:picture).permit(:profile_image, :profile_content, :image, :title, :content, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(mail: params[:session][:mail].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: '新しく作成されました。続けてログインしてください。' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: '新しく作成されました。ログインしていない場合はログインしてください。' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: '削除されました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :mail, :password, :password_confirmation, :profile_image, :profile_content, :image_cache,)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>お気に入り</h1>

  <ul><%= link_to '一覧画面へ', pictures_path %></ul>

  <table>
    <thead>
      <tr>
        <!-- <th>Image</th>
        <th>Title</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr> -->
    </thead>

    <tbody>
      <% @favorites.each do |favorite| %>

        <div class="col-md-6">

          <ul class="row row2">

            <li><h3>投稿者：<%= favorite.picture.user.name %></h3></li>
            <% if favorite.picture.image.url %>
                <li><%= image_tag (favorite.picture.image.url) %></li>
            <% end %>
            <li>タイトル：<%= favorite.picture.title %></li>
            <li><%= favorite.picture.content %></li>
            <li><%= link_to '確認', favorite.picture %></li>
          </ul>

        </div>

      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
     <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "件のエラー") %></h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :picture_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :picture_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<div class="container">
  <p id="notice"><%=%></p>


  <h2><%= current_user.name %>さんのページ</h2>
  <ul class="row">
    <% if current_user.profile_image.url %>
        <td class="col-xs-4"><%= image_tag (current_user.profile_image.url) %></td>
    <% end %>
    <td class="col-xs-8"><%= current_user.profile_content %></td>
  </ul>



  <h2>投稿一覧</h2>

  <ul><%= link_to 'お気に入り画面へGO!!', favorites_path %></ul>
  <ul><%= link_to '新規投稿', new_picture_path %></ul>

  <table>
    <thead>
      <tr>
        <!-- <th>Image</th>
        <th>name</th>
        <th>Title</th>
        <th>Content</th>
        <th colspan="3"></th> -->
      </tr>
    </thead>

    <tbody>
      <% @pictures.each do |picture| %>

        <div class="col-md-6">

          <ul class="row row2">

            <li><h3>投稿者：<%= picture.user.name %></h3></li>

            <% if picture.image.url %>
              <li><%= image_tag (picture.image.url) %></li>
            <% end %>

            <li>タイトル:<%= picture.title %></li>
            <li><%= picture.content %></li>
            <li class="col-xs-4"><%= link_to '確認', picture %></li>

            <% if current_user.id == picture.user.id %>
              <li class="col-xs-4"><%= link_to '編集', edit_picture_path(picture) %></li>
              <li class="col-xs-4"><%= link_to '削除', picture, method: :delete, data: { confirm: '本当に削除しますか?' } %></li>
            <% end %>
          </ul>

        </div>

      <% end %>
    </tbody>
  </table>

  <br>


</div>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p>
  <strong>Image:</strong>
  <% if @picture.image.url %>
    <%= image_tag @picture.image.url %>
  <% end %>
</p>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @picture.content %>
</p>
<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入りを解除する', favorite_path(id: @favorite.id),method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<td><%= link_to 'お気に入り画面へGO!!', favorites_path %></td>


<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "件のエラー") %> </h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail, id: :user_mail %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :プロフィール画像 %>
    <%= form.file_field :profile_image %>
  </div>

  <div class="field">
    <%= form.label :プロフィール内容 %>
    <%= form.text_area :profile_content, id: :user_profile_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> 

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mail</th>
      <th>Password digest</th>
      <th>Profile image</th>
      <th>Profile content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.mail %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.profile_image %></td>
        <td><%= user.profile_content %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<td><%= link_to '投稿画面へGO!!', pictures_path %></td>

<p>
  <strong>名前:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>メール:</strong>
  <%= @user.mail %>
</p>

<p>
  <strong>プロフィール画像:</strong>
  <% if @user.profile_image.url %>
    <%= image_tag @user.profile_image.url %>
  <% end %>
</p>

<p>
  <strong>プロフィール内容:</strong>
  <%= @user.profile_content %>
</p>

<td><%= link_to '編集', edit_user_path %></td>